import 'product.dart';
import 'supplier.dart';

final List<Supplier> seedSuppliers = [
  const Supplier(
    id: 1,
    name: 'Royal Canin',
    country: 'Франция',
    contactPerson: 'Жан-Люк Дюпон',
    phone: '+7 (495) 123-45-67',
    email: 'contact@royalcanin.fr',
    rating: 4.9,
  ),
  const Supplier(
    id: 2,
    name: 'Purina Pro Plan',
    country: 'США',
    contactPerson: 'Марк Джонсон',
    phone: '+7 (495) 234-56-78',
    email: 'info@purina.com',
    rating: 4.8,
  ),
  const Supplier(
    id: 3,
    name: 'Tetra Russia',
    country: 'Германия',
    contactPerson: 'Ганс Шмидт',
    phone: '+7 (495) 345-67-89',
    email: 'support@tetra.net',
    rating: 4.7,
  ),
  const Supplier(
    id: 4,
    name: 'Ferplast',
    country: 'Италия',
    contactPerson: 'Марко Росси',
    phone: '+7 (495) 456-78-90',
    email: 'sales@ferplast.it',
    rating: 4.6,
  ),
  const Supplier(
    id: 5,
    name: 'Beaphar',
    country: 'Нидерланды',
    contactPerson: 'Виллем ван Дейк',
    phone: '+7 (495) 567-89-01',
    email: 'nl@beaphar.com',
    rating: 4.7,
  ),
  const Supplier(
    id: 6,
    name: 'Triol',
    country: 'Россия',
    contactPerson: 'Алексей Иванов',
    phone: '+7 (495) 678-90-12',
    email: 'orders@triol.ru',
    rating: 4.4,
  ),
  const Supplier(
    id: 7,
    name: 'Hill\'s Pet Nutrition',
    country: 'США',
    contactPerson: 'Сара Коннор',
    phone: '+7 (495) 789-01-23',
    email: 'contact@hills.com',
    rating: 4.8,
  ),
  const Supplier(
    id: 8,
    name: 'Whiskas & Pedigree',
    country: 'Россия',
    contactPerson: 'Елена Смирнова',
    phone: '+7 (495) 890-12-34',
    email: 'corp@mars.ru',
    rating: 4.2,
  ),
  const Supplier(
    id: 9,
    name: 'Savic',
    country: 'Бельгия',
    contactPerson: 'Люк де Смет',
    phone: '+7 (495) 901-23-45',
    email: 'info@savic.be',
    rating: 4.5,
  ),
  const Supplier(
    id: 10,
    name: 'Trixie',
    country: 'Германия',
    contactPerson: 'Карл Вебер',
    phone: '+7 (495) 012-34-56',
    email: 'export@trixie.de',
    rating: 4.6,
  ),
];

final List<Product> seedProducts = [
  const Product(
    id: 1,
    name: 'Сухой корм Royal Canin Maxi Adult 15кг',
    sku: 'PET-1001',
    categoryId: 1,
    supplierId: 1,
    price: 6490.0,
    stock: 45,
    rating: 4.9,
    animalTypes: ['Собаки'],
  ),
  const Product(
    id: 2,
    name: 'Влажный корм Purina Pro Plan Sterilised для кошек 85г',
    sku: 'PET-1002',
    categoryId: 1,
    supplierId: 2,
    price: 85.0,
    stock: 350,
    rating: 4.8,
    animalTypes: ['Кошки'],
  ),
  const Product(
    id: 3,
    name: 'Аквариумственный комплект Tetra AquaArt 60L LED',
    sku: 'PET-1003',
    categoryId: 3,
    supplierId: 3,
    price: 14500.0,
    stock: 8,
    rating: 4.9,
    animalTypes: ['Рыбы'],
  ),
  const Product(
    id: 4,
    name: 'Клетка для мелких птиц Ferplast Rekord 3',
    sku: 'PET-1004',
    categoryId: 5,
    supplierId: 4,
    price: 5200.0,
    stock: 12,
    rating: 4.6,
    animalTypes: ['Птицы'],
  ),
  const Product(
    id: 5,
    name: 'Капли от блох и клещей Beaphar Spot-On для собак 3 пипетки',
    sku: 'PET-1005',
    categoryId: 4,
    supplierId: 5,
    price: 890.0,
    stock: 75,
    rating: 4.7,
    animalTypes: ['Собаки'],
  ),
  const Product(
    id: 6,
    name: 'Игрушка для кошек Triol Мышка на пружине с присоской',
    sku: 'PET-1006',
    categoryId: 2,
    supplierId: 6,
    price: 240.0,
    stock: 120,
    rating: 4.3,
    animalTypes: ['Кошки'],
  ),
  const Product(
    id: 7,
    name: 'Лечебный корм Hill\'s Prescription Diet i/d Gastrointestinal 2кг',
    sku: 'PET-1007',
    categoryId: 1,
    supplierId: 7,
    price: 2950.0,
    stock: 22,
    rating: 4.9,
    animalTypes: ['Собаки', 'Кошки'],
  ),
  const Product(
    id: 8,
    name: 'Паучи Whiskas Желе с говядиной 75г',
    sku: 'PET-1008',
    categoryId: 1,
    supplierId: 8,
    price: 32.0,
    stock: 500,
    rating: 4.1,
    animalTypes: ['Кошки'],
  ),
  const Product(
    id: 9,
    name: 'Клетка для грызунов Savic Spilos 50',
    sku: 'PET-1009',
    categoryId: 5,
    supplierId: 9,
    price: 4300.0,
    stock: 15,
    rating: 4.5,
    animalTypes: ['Грызуны'],
  ),
  const Product(
    id: 10,
    name: 'Когтеточка Trixie Когтеточка-столбик 50см',
    sku: 'PET-1010',
    categoryId: 2,
    supplierId: 10,
    price: 1850.0,
    stock: 30,
    rating: 4.6,
    animalTypes: ['Кошки'],
  ),
  const Product(
    id: 11,
    name: 'Сухой корм Royal Canin Kitten для котят 4кг',
    sku: 'PET-1011',
    categoryId: 1,
    supplierId: 1,
    price: 2890.0,
    stock: 60,
    rating: 4.9,
    animalTypes: ['Кошки'],
  ),
  const Product(
    id: 12,
    name: 'Корм для аквариумных рыбок TetraMin Flakes 250мл',
    sku: 'PET-1012',
    categoryId: 3,
    supplierId: 3,
    price: 620.0,
    stock: 90,
    rating: 4.8,
    animalTypes: ['Рыбы'],
  ),
  const Product(
    id: 13,
    name: 'Шампунь противопаразитарный Beaphar 250мл',
    sku: 'PET-1013',
    categoryId: 4,
    supplierId: 5,
    price: 540.0,
    stock: 40,
    rating: 4.5,
    animalTypes: ['Собаки', 'Кошки'],
  ),
  const Product(
    id: 14,
    name: 'Поводок-рулетка Triol Neon 5м до 15кг',
    sku: 'PET-1014',
    categoryId: 5,
    supplierId: 6,
    price: 1290.0,
    stock: 35,
    rating: 4.4,
    animalTypes: ['Собаки'],
  ),
  const Product(
    id: 15,
    name: 'Мячик резиновый Trixie D-6см со свистком',
    sku: 'PET-1015',
    categoryId: 2,
    supplierId: 10,
    price: 290.0,
    stock: 180,
    rating: 4.7,
    animalTypes: ['Собаки'],
  ),
  const Product(
    id: 16,
    name: 'Сухой корм Purina Pro Plan Duo Delice Лосось 10кг',
    sku: 'PET-1016',
    categoryId: 1,
    supplierId: 2,
    price: 5900.0,
    stock: 28,
    rating: 4.8,
    animalTypes: ['Собаки'],
  ),
  const Product(
    id: 17,
    name: 'Фильтр внутренний Tetra EasyCrystal Filter 300',
    sku: 'PET-1017',
    categoryId: 3,
    supplierId: 3,
    price: 2350.0,
    stock: 19,
    rating: 4.7,
    animalTypes: ['Рыбы'],
  ),
  const Product(
    id: 18,
    name: 'Переноска Ferplast Atlas 10 EL для кошек и собак',
    sku: 'PET-1018',
    categoryId: 5,
    supplierId: 4,
    price: 2790.0,
    stock: 25,
    rating: 4.8,
    animalTypes: ['Кошки', 'Собаки'],
  ),
  const Product(
    id: 19,
    name: 'Мультивитамины Beaphar Top 10 для кошек 180 таб',
    sku: 'PET-1019',
    categoryId: 4,
    supplierId: 5,
    price: 990.0,
    stock: 50,
    rating: 4.8,
    animalTypes: ['Кошки'],
  ),
  const Product(
    id: 20,
    name: 'Туннель игривый Trixie для кошек 50см',
    sku: 'PET-1020',
    categoryId: 2,
    supplierId: 10,
    price: 1150.0,
    stock: 20,
    rating: 4.5,
    animalTypes: ['Кошки'],
  ),
  const Product(
    id: 21,
    name: 'Корм для волнистых попугаев Triol 500g',
    sku: 'PET-1021',
    categoryId: 1,
    supplierId: 6,
    price: 190.0,
    stock: 110,
    rating: 4.3,
    animalTypes: ['Птицы'],
  ),
  const Product(
    id: 22,
    name: 'Лакомство Pedigree DentaStix для средних собак 7шт',
    sku: 'PET-1022',
    categoryId: 1,
    supplierId: 8,
    price: 240.0,
    stock: 160,
    rating: 4.6,
    animalTypes: ['Собаки'],
  ),
  const Product(
    id: 23,
    name: 'Поилка автопоилка Savic Aqua Boy 500мл',
    sku: 'PET-1023',
    categoryId: 5,
    supplierId: 9,
    price: 680.0,
    stock: 40,
    rating: 4.4,
    animalTypes: ['Собаки'],
  ),
  const Product(
    id: 24,
    name: 'Терморегулятор Tetra HT 50W для аквариума',
    sku: 'PET-1024',
    categoryId: 3,
    supplierId: 3,
    price: 1980.0,
    stock: 14,
    rating: 4.8,
    animalTypes: ['Рыбы'],
  ),
  const Product(
    id: 25,
    name: 'Спрей Beaphar Отпугивающий для кошек 125мл',
    sku: 'PET-1025',
    categoryId: 4,
    supplierId: 5,
    price: 720.0,
    stock: 33,
    rating: 4.2,
    animalTypes: ['Кошки'],
  ),
];
